apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Values.volume.name }}
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Values.volume.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
