# Default values for cba-chart

# aka "cody-basic-application"
appName: cba

app:
  image:
    repository: codycroth/cba-app
    tag: latest
  containerPort: 8080
  replicaCount: 1

mysql:
  image:
    repository: codycroth/cba-mysql
    tag: latest
  containerPort: 3306
  db_user: root
  db_database: cba_db

ingress:
  appURL: cba.ccr.test

secrets:
  db_pass: <encoded_pass_here>
  secret_key: <encoded_key_here>

volume:
  name: db-volume
  storage: 100Mi
